#!/bin/sh

new_branch=$(git branch --show-current)

# These branches already exist and should always be checked out (and especially not be deleted)
if [[ $new_branch =~ ^dev|release|master$ ]]
then
    exit 0
fi

base_branch=$(git rev-parse --abbrev-ref @{-1})
base_head=$(git rev-parse @{-1})
new_head=$(git rev-parse HEAD)

# First check the name of the base branch
# Then compare the hashes of the last commits
if [ $base_branch = "test" ] && [ $base_head = $new_head ]
then
    echo "-----------------"
    echo "HOLD YOUR HORSES!"
    echo "-----------------"       
    echo "Remember not to create branches from the test branch."
    echo "Switching to dev and deleting the new branch..."
    echo "-----------------"
    git checkout --ignore-other-worktrees dev && git branch -D $new_branch
    exit 1
fi